Add dynamic setting for DiskCircuitBreaker default disk shortage thre…
opensearch-project/ml-commons pull request #1532
Opened 2023-10-20 21:32 UTC by pranavjad

### Description
Adds a dynamic setting for the disk shortage threshold in the DiskCircuitBreaker.

### Issues Resolved
[#1341](https://github.com/opensearch-project/ml-commons/issues/1341)

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-21 18:05 UTC, ylwu-amzn commented
Thanks for making this change. The CI failed, check https://github.com/opensearch-project/ml-commons/actions/runs/6592907739/job/17914444093?pr=1532
```
* What went wrong:
Execution failed for task ':opensearch-ml-plugin:spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/org/opensearch/ml/breaker/DiskCircuitBreaker.java
          @@ -11,9 +11,9 @@
           import·java.security.AccessController;
           import·java.security.PrivilegedActionException;
           import·java.security.PrivilegedExceptionAction;
          +
          +import·org.opensearch.cluster.service.ClusterService;
           import·org.opensearch.common.settings.Settings;
          -import·org.opensearch.cluster.service.ClusterService;
          -
           import·org.opensearch.ml.common.exception.MLException;
           
           /**
          @@ -36,6 +36,7 @@
           ········super(threshold);
           ········this.diskDir·=·diskDir;
           ····}
          +
           ····public·DiskCircuitBreaker(Settings·settings,·ClusterService·clusterService,·String·diskDir)·{
           ········super(DEFAULT_DISK_SHORTAGE_THRESHOLD);
           ········this.diskDir·=·diskDir;
      src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
          @@ -169,14 +169,7 @@
           ········);
           
           ····public·static·final·Setting<Long>·ML_COMMONS_DISK_SHORTAGE_THRESHOLD·=·Setting
          -············.longSetting(
          -················"plugins.ml_commons.disk_shortage_threshold",
          -················5L,
          -················1L,
          -················10L,
          -················Setting.Property.NodeScope,
          -················Setting.Property.Dynamic
          -············);
          +········.longSetting("plugins.ml_commons.disk_shortage_threshold",·5L,·1L,·10L,·Setting.Property.NodeScope,·Setting.Property.Dynamic);
           ····public·static·final·Setting<Boolean>·ML_COMMONS_MEMORY_FEATURE_ENABLED·=·ConversationalIndexConstants.ML_COMMONS_MEMORY_FEATURE_ENABLED;
           
           ····//·Feature·flag·for·enabling·search·processors·for·Retrieval·Augmented·Generation·using·OpenSearch·and·Remote·Inference.
  Run './gradlew :opensearch-ml-plugin:spotlessApply' to fix these violations.
```

2023-10-22 21:16 UTC, pranavjad commented
The integTest seems to be failing, not sure whats going on here.

2023-10-24 05:26 UTC, austintlee commented
See if they are (known) flaky tests.

2023-10-24 05:52 UTC, ylwu-amzn commented
Seems flaky as some platform succeed , some failed, rerun the failed test.

2023-10-25 18:51 UTC, austintlee requested changes
Can you add some tests for this?

2023-10-27 20:39 UTC, pranavjad commented
Is there any reference for adding tests I can look at? I'm not really sure where to add tests or what to test.

2023-10-31 21:43 UTC, dhrubo-os commented
> Is there any reference for adding tests I can look at? I'm not really sure where to add tests or what to test.

Could you please check how other variables were tested? For example `ML_COMMONS_MEMORY_FEATURE_ENABLED` ? 

This will help you to deep dive in the code.

2023-11-05 16:26 UTC, dhrubo-os commented
@pranavjad do you understand now how to add tests? Please let us know if you are still unclear about this.

2023-11-05 17:13 UTC, pranavjad commented
@dhrubo-os  I looked through the test folder under plugin and saw how the tests for MemoryCircuitBreaker and MLCircuitBreaker were made, but when creating a DiskCircuitBreaker object in a test, what should I use as the diskDir argument?

2023-11-05 17:25 UTC, dhrubo-os commented
> @dhrubo-os I looked through the test folder under plugin and saw how the tests for MemoryCircuitBreaker and MLCircuitBreaker were made, but when creating a DiskCircuitBreaker object in a test, what should I use as the diskDir argument?

@Zhangxunmt Looks like you worked in this class. Could you please help @pranavjad? Thanks.

2023-11-20 21:11 UTC, Zhangxunmt approved these changes
Again, can we add one more test case covering this change?

2023-11-20 23:01 UTC, Zhangxunmt commented
https://github.com/opensearch-project/ml-commons/blob/2.x/plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java#L329, Please use this Dir for your tests. @pranavjad

2023-11-22 07:36 UTC, ylwu-amzn commented on plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
> +        .longSetting("plugins.ml_commons.disk_shortage_threshold", 5L, 1L, 10L, Setting.Property.NodeScope, Setting.Property.Dynamic);
How about rename the setting name?
```suggestion
        .longSetting("plugins.ml_commons.disk_space_threshold", 5L, 1L, 10L, Setting.Property.NodeScope, Setting.Property.Dynamic);
```

2024-02-20 22:54 UTC, dhrubo-os commented
@pranavjad are you working on this?

2024-02-20 23:11 UTC, closed without merging

2024-02-20 23:11 UTC, pranavjad commented
No, I am not sorry. I do not think I will be able to finish this PR, so I will close it. Thanks.