Updated Testcases for RemoteModel.java
opensearch-project/ml-commons pull request #1535
Opened 2023-10-23 01:14 UTC by divitr

### Description
Updated Testcases for RemoteModel.java
 
### Issues Resolved
Resolves #1382
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-25 18:48 UTC, austintlee commented
@dhrubo-os do you know why coverage went _down_ with an addition of a test case?

2023-10-25 18:50 UTC, austintlee requested changes
I don't think you are testing the right thing here.

2023-10-25 18:50 UTC, austintlee commented on ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteModelTest.java
> +        Assert.assertTrue(remoteModel.isModelReady());
Is this going to be flaky due to timing?

2023-10-25 18:50 UTC, austintlee commented on ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteModelTest.java
> +    public void predict_ModelPredictSuccess() {
"testXYZ" and no underscore.

2023-10-25 18:50 UTC, austintlee commented on ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteModelTest.java
> +        when(remoteConnectorExecutor.executePredict(mlInput)).thenReturn(new ModelTensorOutput(new ArrayList<>()));
What are you testing??

2023-11-20 21:16 UTC, Zhangxunmt reviewed
I am going to close this PR if there's still no response to Austin's comments. @divitr

2024-09-29 00:30 UTC, closed without merging