Prevents future UT build issues addresses #2967
opensearch-project/ml-commons pull request #2980
Opened 2024-09-24 00:33 UTC by brianf-aws

### Description
Depending on the GitHub CI workflow executes it will invoke ./gradlew build which will run tests on random parameters every time, there are local-code's that will break a build one of them being **az-Cyrl**. The solution here was preventing (by explicitly writing the local to be set to **en-US**) Github actions building on these random parameters that will interrupt a build and lose time. Manual testing was done to prove that using this flag breaks a build, you can check the issue #2967 or you can run (locally) ./gradlew build -Dtests.local=az-Cyrl to see it breaks

**TLDR:**
- This one line change prevents future build fails by manually changing the local code to avoid UT build failures on  `-Dtests.locale=az-Cyrl` if you get unlucky with that randomized build parameter
### Related Issues
Resolves #2967

### Check List
- [X] New functionality includes testing.
- [X] Commits are signed per the DCO using `--signoff`.
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-24 07:40 UTC, dbwiddis requested changes
This seems like the wrong fix for the issue.

There's clearly a locale-based bug somewhere but instead of fixing it you're ignoring it for the entire build, even for tests unaffected by the issue.  This would miss issues such as https://github.com/opensearch-project/ml-commons/pull/1734

All of the failing tests in the linked issue are in the `RestMLPredictionActionTests` class, so if those tests require `en-US` locale that should be scoped only to those tests.  

However, locale based bugs are very frequently using upper- or lower-case string transformations.   This line has a `toUpperCase()` transformation without a locale and is very likely the bug that needs fixing by adding `Locale.ROOT`.  (There may be others.)

https://github.com/opensearch-project/ml-commons/blob/6a6cac13ee1a009ea43a3bad147059578d2adc38/plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java#L132

A brief search of the entire repo shows several similar potential locale issues, you should probably fix them all!
 - https://github.com/search?q=repo%3Aopensearch-project%2Fml-commons%20touppercase()&type=code
 - https://github.com/search?q=repo%3Aopensearch-project%2Fml-commons+tolowercase%28%29&type=code

If you want to go a step further, converting a string by upper/lower casing just for a comparison is inefficient as it creates a whole new string object which is immediately discarded.  If done frequently this adds to the heap/GC load.  Use `.equalsIgnoreCase()` when you can to avoid this extra object creation.

2024-09-24 08:30 UTC, dbwiddis commented
Update: this is the specific bug location, but as noted above you should fix all of them.
https://github.com/opensearch-project/ml-commons/blob/6a6cac13ee1a009ea43a3bad147059578d2adc38/common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java#L211

2024-09-24 17:16 UTC, brianf-aws commented
> This seems like the wrong fix for the issue.
> 
> There's clearly a locale-based bug somewhere but instead of fixing it you're ignoring it for the entire build, even for tests unaffected by the issue. This would miss issues such as #1734
> 
> All of the failing tests in the linked issue are in the `RestMLPredictionActionTests` class, so if those tests require `en-US` locale that should be scoped only to those tests.
> 
> However, locale based bugs are very frequently using upper- or lower-case string transformations. This line has a `toUpperCase()` transformation without a locale and is very likely the bug that needs fixing by adding `Locale.ROOT`. (There may be others.)
> 
> https://github.com/opensearch-project/ml-commons/blob/6a6cac13ee1a009ea43a3bad147059578d2adc38/plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java#L132
> 
> A brief search of the entire repo shows several similar potential locale issues, you should probably fix them all!
> 
> * https://github.com/search?q=repo%3Aopensearch-project%2Fml-commons%20touppercase()&type=code
> * https://github.com/search?q=repo%3Aopensearch-project%2Fml-commons+tolowercase%28%29&type=code
> 
> If you want to go a step further, converting a string by upper/lower casing just for a comparison is inefficient as it creates a whole new string object which is immediately discarded. If done frequently this adds to the heap/GC load. Use `.equalsIgnoreCase()` when you can to avoid this extra object creation.

Hey Dan! Thanks for the insight, I agree with you I did feel skeptical making the change Ill get to work with updating the string methods to use `Local.ROOT`

2024-09-25 00:43 UTC, dhrubo-os approved these changes

2024-09-25 00:44 UTC, dhrubo-os commented
Thanks for making the changes.

2024-09-25 06:08 UTC, dbwiddis approved these changes
LGTM Someone should probably do an org-wide search for these. :)

(Edit: [just did](https://github.com/search?q=org%3Aopensearch-project+touppercase%28%29&type=code) 172 of them!  Holy cow!)

2024-09-26 02:47 UTC, rbhavna approved these changes

2024-09-26 16:42 UTC, merged

2024-09-26 17:49 UTC, ylwu-amzn commented
> LGTM Someone should probably do an org-wide search for these. :)
> 
> (Edit: [just did](https://github.com/search?q=org%3Aopensearch-project+touppercase%28%29&type=code) 172 of them! Holy cow!)

Thanks Dan, can you create issues in the impacted repos ?

2024-09-27 05:23 UTC, dbwiddis commented
> > LGTM Someone should probably do an org-wide search for these. :)
> > (Edit: [just did](https://github.com/search?q=org%3Aopensearch-project+touppercase%28%29&type=code) 172 of them! Holy cow!)
> 
> Thanks Dan, can you create issues for the impacted repos ?

Yep, sometime next week.   Filtering to just Java files it's only 66.