[DRAFT] Primary setup for Multi-tenancy
opensearch-project/ml-commons pull request #3307
Opened 2024-12-30 20:10 UTC by dhrubo-os

### Description

In this PR, I'm just adding the primary setup required for [Multi-tenancy feature](https://github.com/opensearch-project/ml-commons/tree/feature/multi_tenancy). After this PR, I'll start raising other PRs for adding multi-tenancy in connector, model, agents etc.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2025-01-08 22:57 UTC, mingshl commented on plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
> +                                        "You don't have permission to access this connector",
When permission denied, maybe also adding the tenant id and the connector id and name to exception message, so it helps the users to get proper permission.

2025-01-08 22:58 UTC, mingshl commented
@dhrubo-os do we have issues to explain this change?

2025-01-08 23:01 UTC, dhrubo-os commented
> @dhrubo-os do we have issues to explain this change?

RFC: https://github.com/opensearch-project/ml-commons/issues/2358

another issue: https://github.com/opensearch-project/ml-commons/issues/2650

2025-01-08 23:07 UTC, dhrubo-os commented on plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
> +                                        "You don't have permission to access this connector",
This is a Get connector method where customer provided the connector id. So we shouldn't expose any unnecessary information from where customer can take advantage.

2025-01-08 23:08 UTC, dhrubo-os commented on plugin/build.gradle
> +//    implementation "jakarta.json:jakarta.json-api:2.1.3"
done

2025-01-08 23:08 UTC, dhrubo-os commented on plugin/build.gradle
> +
done

2025-01-08 23:09 UTC, dhrubo-os commented on common/src/main/java/org/opensearch/ml/common/settings/SettingsChangeListener.java
> +public interface SettingsChangeListener {
done

2025-01-09 02:27 UTC, brianf-aws requested changes
I didnt get to reviewing the tests but left some comments hope they help :)

2025-01-09 02:27 UTC, brianf-aws commented on plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
> +                ML_COMMONS_MULTI_TENANCY_ENABLED.get(settings)
This part is a little bit hard to follow, maybe we can extract it? I say this because you state you are going to add more in the future too.

2025-01-09 02:27 UTC, brianf-aws commented on plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
> +        } else
same here

2025-01-09 02:27 UTC, brianf-aws commented on plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
> +    public static String getTenantID(Boolean isMultiTenancyEnabled, RestRequest restRequest) {
There happens to be a lot of nesting maybe lets refactor to fail early ([gaurd clause](https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp))? 

```java
 public static String getTenantID(Boolean isMultiTenancyEnabled, RestRequest restRequest) {
   if (!isMultiTenancyEnabled)
        return null;
    Map<String, List<String>> headers = restRequest.getHeaders();
  if (headers == null)
     throw new OpenSearchStatusException("Rest request header can't be null", RestStatus.FORBIDDEN);
  if (!headers.containsKey(Constants.TENANT_ID_HEADER))
      throw new OpenSearchStatusException("Tenant ID header is missing", RestStatus.FORBIDDEN);
  List<String> tenantIdList = headers.get(Constants.TENANT_ID_HEADER);
  
   if (tenantIdList == null || tenantIdList.isEmpty()) 
         throw new OpenSearchStatusException("Tenant ID header is missing", RestStatus.FORBIDDEN);
         
  String tenantId = tenantIdList.get(0);
  if (tenantId == null)
       throw new OpenSearchStatusException("Tenant ID can't be null", RestStatus.FORBIDDEN);
               
    return tenantId
}

```

My indentation is off but the point is to check your edge cases first and let it trickle down to the happy case

2025-01-09 14:49 UTC, dhrubo-os commented on plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
> +                ML_COMMONS_MULTI_TENANCY_ENABLED.get(settings)
We are just building the SDKClient here. Similar like [this](https://github.com/opensearch-project/flow-framework/pull/980/files#diff-9d60d6086ce87e2240d7d6bcf8d2a8b79c73400fc6ec6865f74fc571e03bf1af)

2025-01-09 14:52 UTC, dhrubo-os commented on plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
> +        if (mlFeatureEnabledSetting.isMultiTenancyEnabled() && tenantId == null) {
From the plugin level, we don't have visibility if the tenant id is valid or not. We perform this validation from the interceptor level. Here we just check if multi-tenancy is enabled then tenant id needs to be present.

2025-01-09 15:00 UTC, dhrubo-os commented on plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
> +                        String tenantId = tenantIdList.get(0);
HTTP headers are represented as a Map<String, List<String>> because the HTTP protocol allows multiple values for a single header key (e.g., Set-Cookie). Even though most headers, like Tenant-ID, typically have only one value, the list structure ensures flexibility and compatibility. In practice, we usually retrieve the first value (list.get(0)) since only one value is needed in most cases.

2025-01-09 15:55 UTC, dhrubo-os commented on plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
> +        .simpleString("plugins.ml_commons." + REMOTE_METADATA_TYPE_KEY, Setting.Property.NodeScope, Setting.Property.Final);
Nice!!

2025-01-09 15:56 UTC, dhrubo-os commented on plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
> +    public static String getTenantID(Boolean isMultiTenancyEnabled, RestRequest restRequest) {
Yeah this is better.

2025-01-10 00:23 UTC, dhrubo-os commented
```
Tests with failures:
 - org.opensearch.ml.tools.VisualizationsToolIT.testVisualizationNotFound
 - org.opensearch.ml.tools.VisualizationsToolIT.testVisualizationFound
111 tests completed, 2 failed, 10 skipped
```


Same flaky errors

2025-01-10 01:47 UTC, b4sjoo commented on ml-algorithms/build.gradle
> +    resolutionStrategy.force 'software.amazon.awssdk:bom:2.29.12'
Do you know why use a force here? If the version matter then you should be aware that it will cause version conflict when goes to the managed service.

2025-01-10 02:04 UTC, dhrubo-os commented on ml-algorithms/build.gradle
> +    resolutionStrategy.force 'software.amazon.awssdk:bom:2.29.12'
refer to this: https://github.com/opensearch-project/opensearch-remote-metadata-sdk/pull/25#issuecomment-2580952651

2025-01-10 02:07 UTC, mingshl approved these changes

2025-01-10 04:37 UTC, dbwiddis commented on plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
> +    public static String getTenantID(Boolean isMultiTenancyEnabled, RestRequest restRequest) {
> if (headers == null)
>     throw new OpenSearchStatusException("Rest request header can't be null", RestStatus.FORBIDDEN);

FYI, this case is impossible.  I tried to write a unit test for the Flow Framework version of this util and could not (short of using reflection) make the headers null.  The only way to make it null is using a constructor, where it passes through a `headers.get()` to get the content type from the header; and if that didn't stop it, `Collections.unmodifiableMap()` [would throw an NPE on null headers](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/java/util/Collections.java#L1443-L1444) as well.

2025-01-10 10:54 UTC, b4sjoo approved these changes

2025-01-10 15:06 UTC, merged

2025-01-12 06:38 UTC, dhrubo-os commented on plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
> +    public static String getTenantID(Boolean isMultiTenancyEnabled, RestRequest restRequest) {
Yeah, that's a good point! I agree but I prefer to still keep this as a defensive coding practice.